SOURCES=main.cpp
THIRD_PARTY_SOURCE=$(shell find ./thirdparty -name "*.cpp")

CXXFLAGS = -g -std=c++17
INCLUDES = -Ithirdparty
SRCS = ${SOURCES} ${THIRD_PARTY_SOURCE}
OBJS = $(SRCS:.cpp=.o)
MAIN = game

.PHONY: depend clean

all: $(MAIN)
		@echo  Finished

$(MAIN): $(OBJS) 
		$(CXX) $(CXXFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS)

.cpp.o:
		@echo Compiling $@
		$(CXX) $(CXXFLAGS) $(INCLUDES) -c $<  -o $@ 

clean:
		find . -type f -name "*.o" -delete
		$(RM) ${MAIN}
		$(RM) -rf -- ${MAIN}.dSYM


depend: $(SRCS)
		makedepend $(INCLUDES) $^

# DO NOT DELETE

main.o: thirdparty/Box2D/Box2D.h thirdparty/Box2D/Common/b2Settings.h
main.o: thirdparty/Box2D/Common/b2Draw.h thirdparty/Box2D/Common/b2Math.h
main.o: thirdparty/Box2D/Common/b2Timer.h
main.o: thirdparty/Box2D/Collision/Shapes/b2CircleShape.h
main.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
main.o: thirdparty/Box2D/Common/b2BlockAllocator.h
main.o: thirdparty/Box2D/Collision/b2Collision.h
main.o: thirdparty/Box2D/Collision/Shapes/b2EdgeShape.h
main.o: thirdparty/Box2D/Collision/Shapes/b2ChainShape.h
main.o: thirdparty/Box2D/Collision/Shapes/b2PolygonShape.h
main.o: thirdparty/Box2D/Collision/b2BroadPhase.h
main.o: thirdparty/Box2D/Collision/b2DynamicTree.h
main.o: thirdparty/Box2D/Common/b2GrowableStack.h
main.o: thirdparty/Box2D/Collision/b2Distance.h
main.o: thirdparty/Box2D/Collision/b2TimeOfImpact.h
main.o: thirdparty/Box2D/Dynamics/b2Body.h
main.o: thirdparty/Box2D/Dynamics/b2Fixture.h
main.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
main.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
main.o: thirdparty/Box2D/Dynamics/b2World.h
main.o: thirdparty/Box2D/Common/b2StackAllocator.h
main.o: thirdparty/Box2D/Dynamics/b2ContactManager.h
main.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2GearJoint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.h
main.o: thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Dynamics/b2World.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Common/b2StackAllocator.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Dynamics/b2ContactManager.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Collision/b2BroadPhase.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Collision/b2DynamicTree.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Common/b2GrowableStack.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/b2Body.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/b2World.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Common/b2StackAllocator.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/b2ContactManager.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Collision/b2BroadPhase.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Collision/b2DynamicTree.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Common/b2GrowableStack.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/b2Island.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Collision/Shapes/b2CircleShape.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Collision/Shapes/b2EdgeShape.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Collision/Shapes/b2ChainShape.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Collision/Shapes/b2PolygonShape.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Collision/b2TimeOfImpact.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Collision/b2Distance.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Common/b2Draw.h
thirdparty/Box2D/Dynamics/b2World.o: thirdparty/Box2D/Common/b2Timer.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Dynamics/b2World.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Common/b2StackAllocator.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Dynamics/b2ContactManager.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Collision/b2BroadPhase.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Collision/b2DynamicTree.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Common/b2GrowableStack.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Collision/Shapes/b2CircleShape.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Collision/Shapes/b2EdgeShape.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Collision/Shapes/b2PolygonShape.h
thirdparty/Box2D/Dynamics/b2Fixture.o: thirdparty/Box2D/Collision/Shapes/b2ChainShape.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Collision/Shapes/b2ChainShape.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.o: thirdparty/Box2D/Collision/Shapes/b2EdgeShape.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.o: thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Collision/Shapes/b2ChainShape.h
thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.o: thirdparty/Box2D/Collision/Shapes/b2EdgeShape.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.o: thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Collision/b2TimeOfImpact.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Collision/b2Distance.h
thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Dynamics/b2World.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Common/b2StackAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Dynamics/b2ContactManager.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Collision/b2BroadPhase.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Collision/b2DynamicTree.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Common/b2GrowableStack.h
thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Collision/b2TimeOfImpact.h
thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.o: thirdparty/Box2D/Collision/b2Distance.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.o: thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/Contacts/b2CircleContact.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/Contacts/b2PolygonContact.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Collision/b2TimeOfImpact.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Collision/b2Distance.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/b2World.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Common/b2StackAllocator.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/b2ContactManager.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Collision/b2BroadPhase.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Collision/b2DynamicTree.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Common/b2GrowableStack.h
thirdparty/Box2D/Dynamics/Contacts/b2Contact.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/b2WorldCallbacks.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/b2WorldCallbacks.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/b2WorldCallbacks.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/b2WorldCallbacks.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/b2WorldCallbacks.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/b2WorldCallbacks.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/b2WorldCallbacks.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/b2WorldCallbacks.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.o: thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.h
thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.o: thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.h
thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.o: thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.h
thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.o: thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.h
thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.o: thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.h
thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.o: thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.h
thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.o: thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.h
thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Dynamics/Joints/b2GearJoint.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2GearJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2DistanceJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2WheelJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2MouseJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2RevoluteJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2GearJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2WeldJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2FrictionJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/Joints/b2MotorJoint.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/b2World.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Common/b2StackAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/b2ContactManager.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Collision/b2BroadPhase.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Collision/b2DynamicTree.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Common/b2GrowableStack.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/Joints/b2Joint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.o: thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.h
thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2PrismaticJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.o: thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.h
thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2PulleyJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.o: thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.h
thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/Joints/b2RopeJoint.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Collision/b2Distance.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Dynamics/b2Island.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Dynamics/b2TimeStep.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Dynamics/b2World.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Common/b2StackAllocator.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Dynamics/b2ContactManager.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Collision/b2BroadPhase.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Collision/b2DynamicTree.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Common/b2GrowableStack.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Dynamics/Contacts/b2ContactSolver.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Dynamics/Joints/b2Joint.h
thirdparty/Box2D/Dynamics/b2Island.o: thirdparty/Box2D/Common/b2Timer.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Dynamics/b2ContactManager.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Collision/b2BroadPhase.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Collision/b2DynamicTree.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Common/b2GrowableStack.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Dynamics/b2Body.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Dynamics/b2Fixture.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Dynamics/b2WorldCallbacks.h
thirdparty/Box2D/Dynamics/b2ContactManager.o: thirdparty/Box2D/Dynamics/Contacts/b2Contact.h
thirdparty/Box2D/Rope/b2Rope.o: thirdparty/Box2D/Rope/b2Rope.h
thirdparty/Box2D/Rope/b2Rope.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Rope/b2Rope.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Rope/b2Rope.o: thirdparty/Box2D/Common/b2Draw.h
thirdparty/Box2D/Common/b2Draw.o: thirdparty/Box2D/Common/b2Draw.h
thirdparty/Box2D/Common/b2Draw.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Common/b2Draw.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Common/b2BlockAllocator.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Common/b2BlockAllocator.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Common/b2Settings.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Common/b2Timer.o: thirdparty/Box2D/Common/b2Timer.h
thirdparty/Box2D/Common/b2Timer.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Common/b2StackAllocator.o: thirdparty/Box2D/Common/b2StackAllocator.h
thirdparty/Box2D/Common/b2StackAllocator.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Common/b2StackAllocator.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Common/b2Math.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Common/b2Math.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/b2Distance.o: thirdparty/Box2D/Collision/b2Distance.h
thirdparty/Box2D/Collision/b2Distance.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/b2Distance.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/b2Distance.o: thirdparty/Box2D/Collision/Shapes/b2CircleShape.h
thirdparty/Box2D/Collision/b2Distance.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Collision/b2Distance.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Collision/b2Distance.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/b2Distance.o: thirdparty/Box2D/Collision/Shapes/b2EdgeShape.h
thirdparty/Box2D/Collision/b2Distance.o: thirdparty/Box2D/Collision/Shapes/b2ChainShape.h
thirdparty/Box2D/Collision/b2Distance.o: thirdparty/Box2D/Collision/Shapes/b2PolygonShape.h
thirdparty/Box2D/Collision/b2CollideCircle.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/b2CollideCircle.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/b2CollideCircle.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/b2CollideCircle.o: thirdparty/Box2D/Collision/Shapes/b2CircleShape.h
thirdparty/Box2D/Collision/b2CollideCircle.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Collision/b2CollideCircle.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Collision/b2CollideCircle.o: thirdparty/Box2D/Collision/Shapes/b2PolygonShape.h
thirdparty/Box2D/Collision/b2CollidePolygon.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/b2CollidePolygon.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/b2CollidePolygon.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/b2CollidePolygon.o: thirdparty/Box2D/Collision/Shapes/b2PolygonShape.h
thirdparty/Box2D/Collision/b2CollidePolygon.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Collision/b2CollidePolygon.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Collision/b2DynamicTree.o: thirdparty/Box2D/Collision/b2DynamicTree.h
thirdparty/Box2D/Collision/b2DynamicTree.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/b2DynamicTree.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/b2DynamicTree.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/b2DynamicTree.o: thirdparty/Box2D/Common/b2GrowableStack.h
thirdparty/Box2D/Collision/Shapes/b2ChainShape.o: thirdparty/Box2D/Collision/Shapes/b2ChainShape.h
thirdparty/Box2D/Collision/Shapes/b2ChainShape.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Collision/Shapes/b2ChainShape.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Collision/Shapes/b2ChainShape.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/Shapes/b2ChainShape.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/Shapes/b2ChainShape.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/Shapes/b2ChainShape.o: thirdparty/Box2D/Collision/Shapes/b2EdgeShape.h
thirdparty/Box2D/Collision/Shapes/b2EdgeShape.o: thirdparty/Box2D/Collision/Shapes/b2EdgeShape.h
thirdparty/Box2D/Collision/Shapes/b2EdgeShape.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Collision/Shapes/b2EdgeShape.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Collision/Shapes/b2EdgeShape.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/Shapes/b2EdgeShape.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/Shapes/b2EdgeShape.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/Shapes/b2CircleShape.o: thirdparty/Box2D/Collision/Shapes/b2CircleShape.h
thirdparty/Box2D/Collision/Shapes/b2CircleShape.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Collision/Shapes/b2CircleShape.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Collision/Shapes/b2CircleShape.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/Shapes/b2CircleShape.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/Shapes/b2CircleShape.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/Shapes/b2PolygonShape.o: thirdparty/Box2D/Collision/Shapes/b2PolygonShape.h
thirdparty/Box2D/Collision/Shapes/b2PolygonShape.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Collision/Shapes/b2PolygonShape.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Collision/Shapes/b2PolygonShape.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/Shapes/b2PolygonShape.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/Shapes/b2PolygonShape.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/b2TimeOfImpact.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/b2TimeOfImpact.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/b2TimeOfImpact.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/b2TimeOfImpact.o: thirdparty/Box2D/Collision/b2Distance.h
thirdparty/Box2D/Collision/b2TimeOfImpact.o: thirdparty/Box2D/Collision/b2TimeOfImpact.h
thirdparty/Box2D/Collision/b2TimeOfImpact.o: thirdparty/Box2D/Collision/Shapes/b2CircleShape.h
thirdparty/Box2D/Collision/b2TimeOfImpact.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Collision/b2TimeOfImpact.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Collision/b2TimeOfImpact.o: thirdparty/Box2D/Collision/Shapes/b2PolygonShape.h
thirdparty/Box2D/Collision/b2TimeOfImpact.o: thirdparty/Box2D/Common/b2Timer.h
thirdparty/Box2D/Collision/b2BroadPhase.o: thirdparty/Box2D/Collision/b2BroadPhase.h
thirdparty/Box2D/Collision/b2BroadPhase.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/b2BroadPhase.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/b2BroadPhase.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/b2BroadPhase.o: thirdparty/Box2D/Collision/b2DynamicTree.h
thirdparty/Box2D/Collision/b2BroadPhase.o: thirdparty/Box2D/Common/b2GrowableStack.h
thirdparty/Box2D/Collision/b2CollideEdge.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/b2CollideEdge.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/b2CollideEdge.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/b2CollideEdge.o: thirdparty/Box2D/Collision/Shapes/b2CircleShape.h
thirdparty/Box2D/Collision/b2CollideEdge.o: thirdparty/Box2D/Collision/Shapes/b2Shape.h
thirdparty/Box2D/Collision/b2CollideEdge.o: thirdparty/Box2D/Common/b2BlockAllocator.h
thirdparty/Box2D/Collision/b2CollideEdge.o: thirdparty/Box2D/Collision/Shapes/b2EdgeShape.h
thirdparty/Box2D/Collision/b2CollideEdge.o: thirdparty/Box2D/Collision/Shapes/b2PolygonShape.h
thirdparty/Box2D/Collision/b2Collision.o: thirdparty/Box2D/Collision/b2Collision.h
thirdparty/Box2D/Collision/b2Collision.o: thirdparty/Box2D/Common/b2Math.h
thirdparty/Box2D/Collision/b2Collision.o: thirdparty/Box2D/Common/b2Settings.h
thirdparty/Box2D/Collision/b2Collision.o: thirdparty/Box2D/Collision/b2Distance.h
